# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f3251267e8f8c41f3719a1c482eeafea4dbc9b86146e4313b81a0cc4b845245c4098da3df4b38bdda7c9c00228e8e80f10db47c7faa58fef597e4a3e9118c67

test:
  secret_key_base: f6e66a63ad2c36f978621f50ff89ba8995538ec3ce1b3b1fab83dabe20cddd33bbd7155a73fc21ce053b6d1d40edcdbac6b98365f6cbd80348e477fdc00a3b1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
